
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
ENV PORT=10000
ENV APP_MODE=cloud
CMD uvicorn main:app --host 0.0.0.0 --port ${PORT}
